### ISSUE TITLE
error al guardar 2 veces

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/huayra-caripela#3]
Al guardar 2 veces seguidas el avatar hay una excepcion:

Uncaught node.js Error 

TypeError: Cannot read property 'objects' of null
    at Object.Canvas.guardar (file:///home/ftoledo/conectar/paquetes/huayra-caripela/src/js/factories/CanvasFactory.js:341:47)
    at window.fn_guardar_y_regresar (file:///home/ftoledo/conectar/paquetes/huayra-caripela/src/js/controllers/EditorCtrl.js:255:12)
    at MenuItem.item_guardar.gui.MenuItem.click (file:///home/ftoledo/conectar/paquetes/huayra-caripela/src/js/services/menu.js:14:20)
    at MenuItem.handleEvent (menuitem.js:171:12)
    at IDWeakMap.global.__nwObjectsRegistry.handleEvent (node.js:795:26)

**Comment by hugoruscitti** [comment]
Supongo que era un bug antiguo que teníamos con el menú anterior. En la versión 0.27 parece resuelto.
